### PR TITLE
Feat: Initial load of regions according to ISO-3166-2 from CSV File

### PR DESCRIPTION
**Pull request by rainer-exxcellent**
## Description

Read regions from CSV-File and generate a SQL script.
Copy the generated script by hand into the migration files directory.

### TODO

A new dependency has been added to the pom.xml (Apache Commons CSV)
Licence needs to be clarified.

### CODE REVIEW

**Comment by nicoprow** [comment]
Created IP-Issue for the used CSV list: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10183

**Review by nicoprow — CHANGES_REQUESTED** [review]
The license is approved but the information about the license should be included in the project root NOTICE file. 

I propose to add the license under the licenses header and specify which part of the source code is affected by this license.

**Comment by rainer-exxcellent** [comment]
I added a license information to the NOTICE file.

**Review by nicoprow — COMMENTED** [review]
I rerequested a review from Eclipse to make sure that the changes of the Notice file are alright. Meanwhile if it takes longer than anticipated I would approve and merge the pull request. In case there are changes needed we can always adapt the Notice file later on.

**Comment by rainer-exxcellent** [comment]
I rebased the branch to the current main

**Review by nicoprow — APPROVED** [review]

**Comment by nicoprow** [comment]
Any feedback on changes to the Notice file will be incorporated in a next pull request, if any changes are needed

**Pull request merged**
