### PR TITLE
chore(bpdm): remove reference to pull request from other Github org

### PR DESCRIPTION
**Pull request by SujitMBRDI**
## Description

In this pull request, we have removed reference from other Github org

## Why

will be a dead link soon as the org is supposed to be deleted

## Issue
https://github.com/eclipse-tractusx/bpdm/issues/1054 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by SujitMBRDI** [comment]
Hi @stephanbcbauer 
Can you help to confirm on CHANGELOG entries from [this](https://github.com/search?q=org%3Aeclipse-tractusx+catenax-ng++repo%3Aeclipse-tractusx%2Fbpdm&type=code) query as it being fetched due to matching keyword?
Does it make sense to alter old change logs.

**Review by stephanbcbauer — APPROVED** [review]
LGTM

**Comment by stephanbcbauer** [comment]
> Hi @stephanbcbauer 
> 
> Can you help to confirm on CHANGELOG entries from [this](https://github.com/search?q=org%3Aeclipse-tractusx+catenax-ng++repo%3Aeclipse-tractusx%2Fbpdm&type=code) query as it being fetched due to matching keyword?
> 
> Does it make sense to alter old change logs.

Thx. Since change log manages the changes, it makes sense to not adapt them. In my point of view:)

**Comment by SujitMBRDI** [comment]
> > Hi @stephanbcbauer
> > Can you help to confirm on CHANGELOG entries from [this](https://github.com/search?q=org%3Aeclipse-tractusx+catenax-ng++repo%3Aeclipse-tractusx%2Fbpdm&type=code) query as it being fetched due to matching keyword?
> > Does it make sense to alter old change logs.
> 
> Thx. Since change log manages the changes, it makes sense to not adapt them. In my point of view:)

Thank you :)

**Review by nicoprow — APPROVED** [review]

**Pull request merged**
