### PR TITLE
Docs: Postman collection of automated test for EDC

### PR DESCRIPTION
**Pull request by SujitMBRDI**
## Description
This pull request contains postman collection for automated tests in EDC. where user can change environment details as per the need and perform actions like Query the catalog, Initiate Negotiation and get authentication code to hit public api. All the steps can be performed using postman run for created collection.

## How to Test
Create INT or any specific environment variables then import EDC-BPDM Automated Test.postman_collection.json into postman.After importing, simply run collection and result will show passed and failed test cases in postman.

### CODE REVIEW

**Comment by alexsilva-CGI** [comment]
Collection runs fine, and tests work as well. Looks good from my side.

**Review by nicoprow — CHANGES_REQUESTED** [review]
This postman collection is a very good addition to our EDC documentation as it is basically an upgrade to the existing EDC usage postman collection found here: https://github.com/eclipse-tractusx/bpdm/blob/main/docs/edc/EDC_BPDM_Usage.postman_collection.json

I would propose to change the pull request in such a way that you overwrite that postman collection.

Havin said that, this is not what I expect an automated postman collection to be. My expectation would be to have a postman collection like in here https://github.com/eclipse-tractusx/bpdm/blob/main/docs/postman/automated-test/BPDM%20Automated%20Test.postman_collection.json
Same types of requests but with EDC negotations in between to perform these requests over EDC

**Comment by SujitMBRDI** [comment]
> This postman collection is a very good addition to our EDC documentation as it is basically an upgrade to the existing EDC usage postman collection found here: https://github.com/eclipse-tractusx/bpdm/blob/main/docs/edc/EDC_BPDM_Usage.postman_collection.json
> 
> I would propose to change the pull request in such a way that you overwrite that postman collection.
> 
> Havin said that, this is not what I expect an automated postman collection to be. My expectation would be to have a postman collection like in here https://github.com/eclipse-tractusx/bpdm/blob/main/docs/postman/automated-test/BPDM%20Automated%20Test.postman_collection.json Same types of requests but with EDC negotations in between to perform these requests over EDC

I have added changes as per the review commets, i have adapted changes in two steps. In first step, i am fetching all assetIds and offerIds by querying catelog so user can simply go and access endpoints as per the need from step 2 and those are self explanatory.  I think this is great addition for user who will use this collection so they can simply go and try for endpoint from Gate/Pool using two simple steps.

**Review by nicoprow — APPROVED** [review]
Looks good to me

**Pull request merged**
