### PR TITLE
chore(TRG-7): update licensing and legal docs

### PR DESCRIPTION
**Pull request by SujitMBRDI**
## Description

- Updated licensing and legal docs

## Why
#956 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by nicoprow — CHANGES_REQUESTED** [review]
There is still an old link to the CC-BY-4.0 license in the NOTICE file. This would need to be changed to the license file in the bpdm-pool resources regions folder. Other than that, looks good to me.

**Comment by SujitMBRDI** [comment]
> There is still an old link to the CC-BY-4.0 license in the NOTICE file. This would need to be changed to the license file in the bpdm-pool resources regions folder. Other than that, looks good to me.

@nicoprow, I have removed old license file from bpdm-pool resources and also, updated correct link to CC-BY-4.0 license in the NOTICE file. I kept only one LICENSE_non-code file. Hope it is ok.

**Comment by nicoprow** [comment]
> > There is still an old link to the CC-BY-4.0 license in the NOTICE file. This would need to be changed to the license file in the bpdm-pool resources regions folder. Other than that, looks good to me.
> 
> @nicoprow, I have removed old license file from bpdm-pool resources and also, updated correct link to CC-BY-4.0 license in the NOTICE file. I kept only one LICENSE_non-code file. Hope it is ok.

@SujitMBRDI sorry, I was not clear on that part. That license file must stay as it is part of third party content that we use in our project. We have to keep the license at the same place as the third party file we use in our project. The NOTICE for the thirs party content still needs to point to the license file in the resources and this license file can't be deleted.

In doubt, we need to consult in Eclipse but I'm pretty sure that's how we need to do it

**Comment by SujitMBRDI** [comment]
> > > There is still an old link to the CC-BY-4.0 license in the NOTICE file. This would need to be changed to the license file in the bpdm-pool resources regions folder. Other than that, looks good to me.
> > 
> > 
> > @nicoprow, I have removed old license file from bpdm-pool resources and also, updated correct link to CC-BY-4.0 license in the NOTICE file. I kept only one LICENSE_non-code file. Hope it is ok.
> 
> @SujitMBRDI sorry, I was not clear on that part. That license file must stay as it is part of third party content that we use in our project. We have to keep the license at the same place as the third party file we use in our project. The NOTICE for the thirs party content still needs to point to the license file in the resources and this license file can't be deleted.
> 
> In doubt, we need to consult in Eclipse but I'm pretty sure that's how we need to do it

@nicoprow, I have adapted changes in the way suggested.

Hi @AngelikaWittek, just wanted to confirm about correctness of the declaring third party content and mandatory change in licensing in our repository.
In our notice file we have mentioned third party content as below, where we provided absolute path for third party license file.
```
## Third-party Content

This project leverages the following third party content.

### Dependencies

See [DEPENDENCIES](DEPENDENCIES) file.

### Administrative Areas Level 1

- Description: CSV file content for ISO-3166-2
- SPDX-License-Identifier: [CC-BY-4.0](bpdm-pool/src/main/resources/regions/LICENSE.TXT)
- File Location: [IP2LOCATION-ISO3166-2.CSV](bpdm-pool/src/main/resources/regions/IP2LOCATION-ISO3166-2.CSV)
- Source URL: https://www.ip2location.com
```

**Review by nicoprow — APPROVED** [review]

**Comment by AngelikaWittek** [comment]
Hi, if you want to reference a license (CC-BY-4.0), then  link to the source:
[CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/legalcode).
See also TRG 7.08.
And please review in your team.

Angelika

**Pull request merged**
